input TokenId{
   access_id: String
   access: String
   refresh_token: String
}

type DecodedToken{
    access_id: String
    access: String
    token: String
}

type Mutation{
    JWT(data: TokenId!): DecodedToken!
}

