    input UsuarioTypeInput{
        name: String
        email: String
        age: Int 
        phone: String
    }

    type Usuario{
        id: Int 
        name: String
        email: String
        age: Int 
        phone: String
        permissao: permissoes
    }

    type Mutation{
        criarUsuario(data: UsuarioTypeInput): Usuario!
    }