    input UserInput{
        email: String
        token: String
    }
    
    type Usuario{
        id: String
        name: String
        email: String
        phone: String
        permissao: permissoes
        refresh_token: RefreshToken 
    }
    
    type Query{
        usuarios: [Usuario]
        usuario(data: UserInput): Usuario
    }   

