    input UserInput{
        email: String
        token: String
    }
    
    type Usuario{
        id: Int 
        name: String
        email: String      
        permissao: permissoes
        token_id: String
    }
    type Query{
        usuarios: [Usuario]
        usuario(data: UserInput): Usuario
    }   

