    input UsuarioTypeInput{
        name: String
        email: String
        phone: String
        access: String
    }

    type RefreshToken{
        id:       String 
        expireIn: Int
        user:     Usuario  
        userId:   String     
    }

    type Usuario{
        name: String
        email: String
        phone: String
        permissao: permissoes
        refresh_token: RefreshToken
    }

    type Mutation{
        criarUsuario(data: UsuarioTypeInput): Usuario!
    }