    input UsuarioTypeInput{
        name: String
        email: String
        phone: String
        access: String
    }

    type Usuario{
        refresh_token: String
        name: String
        email: String
        phone: String
        permissao: permissoes
    }

    type Mutation{
        criarUsuario(data: UsuarioTypeInput): Usuario
    }