    input UsuarioTypeInput{
        access_id: Int
        name: String
        email: String
        age: Int 
        phone: String
    }


    type Usuario{
        id: Int 
        name: String
        email: String
        phone: String
        permissao: permissoes
    }

    type Mutation{
        AtualizarUsuario(id: Int!, data: UsuarioTypeInput): Usuario!
    }